### ISSUE TITLE
how to build 2.3.1 use cocoapods

### ISSUE THREAD

**Issue by codercd** [ReactiveX/RxSwift#609]
target 'YOUR_TARGET_NAME' do
    pod 'RxSwift',    '~> 2.3'  ` or  '~> 2.3.1'`
    pod 'RxCocoa',    '~> 2.3'
    pod 'RxBlocking', '~> 2.3'
    pod 'RxTests',    '~> 2.3'
end

```
Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Frame`: (``)

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `RxSwift (~> 2.3.1)` required by `Podfile`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:411:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by kzaher** [comment]
Hi @codercd ,

Have you tried upgrading cocoa pods and making sure that:
* you project has minimal target version of iOS 8.0
* `use_frameworks!`

```
        use_frameworks!

	target 'YOUR_TARGET_NAME' do
		pod 'RxSwift', "~> 2.0"
		pod 'RxCocoa', "~> 2.0"
	end
```

**Comment by codercd** [comment]
@kzaher Thanks for your reply, it's working without  `pod 'RxTests', '~> 2.0'` .
If  `pod 'RxTests', '~> 2.0'` , will get an error: `Cannot invoke 'XCTAssertEqual' with an argument list of type '([AnyEquatable<Event<T>>], [AnyEquatable<Event<T>>], file: String, line: UInt)'`

shouldn't I  `pod 'RxTests'`?

pod version `0.39.0` and `1.0.0.beta.6 ` 

xcode version 7.3

deployment target 9.3

podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.15.0'
target 'Test1' do
    pod 'RxSwift', "~> 2.0"
    pod 'RxCocoa', "~> 2.0"
    pod 'RxBlocking', "~> 2.0"
    pod 'RxTests', '~> 2.0'
end
```
And ,I notice that:
```
-> Using RxBlocking (2.2.0)

-> Using RxCocoa (2.2.0)

-> Using RxSwift (2.2.0)

-> Using RxTests (2.2.0)
```
Is use version 2.2.0?

**Comment by codercd** [comment]
@kzaher Thanks for your peply,I update cocoapods, and It's working.
But,it seems like conflict with [SnapKit](https://github.com/SnapKit/SnapKit)
when i using both `RxSwift` and `SnapKit` ,will be crash:
```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/XXXXXXX/Library/Developer/CoreSimulator/Devices/A0606724-2CA1-4CDD-9615-504DE5671318/data/Containers/Bundle/Application/8B40573A-A98D-4C17-A0AE-AC0F88481B2B/test2.app/Frameworks/RxTests.framework/RxTests
  Reason: image not found
```
It's strange.
should I open an issue  in `Snapkit` or `Cocoapods`?

**Comment by kzaher** [comment]
Hi @codercd ,

Maybe report this to CocoaPods team?

I would suggest first trying to readd CocoaPods integration. When something like this happens to me, I usually remove CocoaPods build steps, remove CocoaPods configurations, `Pods` directory and then do

`pod install`

¯\\\_(ツ)\_/¯

**Comment by codercd** [comment]
Thank you very mush.I have tried ,but it doesn't work ,I'll  report this to CocoaPods team.
