### ISSUE TITLE
CocoaDocs documentation broken on 2.4 release

### ISSUE THREAD

**Issue by shams-ahmed** [ReactiveX/RxSwift#619]
See: http://cocoadocs.org/docsets/RxSwift/2.4

Does this issue fall under RxSwift maintainers?

Error logs from: http://api.cocoadocs.org:4567/error/rxswift/2.4

```
report_error(
{
message: "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--module-name", "RxSwift", "-target", "Pods-Jazzy-RxSwift-ios-RxSwift"] Running xcodebuild Parsing AddRef.swift (1/139) Parsing Amb.swift (2/139) sourcekit: [1:connection-event-handler:4619: 0.0000] Connection interrupt sourcekit: [1:pingService:4619: 0.0723] pinging service sourcekit: [1:sourcekitd_send_request_sync:1547: 0.0725] request dropped while restoring service ",
trace: [
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command'",
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'",
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/podspec_documenter.rb:18:in `block (2 levels) in sourcekitten_output'",
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/podspec_documenter.rb:17:in `map'",
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/podspec_documenter.rb:17:in `block in sourcekitten_output'",
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/podspec_documenter.rb:16:in `chdir'",
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/podspec_documenter.rb:16:in `sourcekitten_output'",
"/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:53:in `build'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:451:in `document_spec'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:541:in `document_spec_at_path'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:165:in `block in doc'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:160:in `each'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:160:in `doc'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:232:in `block in cocoadocs_url'",
"/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'",
"/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'",
"/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:229:in `cocoadocs_url'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:180:in `cocoadocs'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:115:in `initialize'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:573:in `new'",
"/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:573:in `<main>'"
]
}
)
```

**Comment by fpillet** [comment]
I've seen it too and it's a pain. This is an issue with CocoaPods' doc generation, but in the end this is really SourceKit crashing while parsing the code to generate the docs :(

**Comment by kzaher** [comment]
Hi @shams-ahmed ,

I'm not sure on which side is this bug. We've made sure it works fine with CocoaPods. I was assuming that once you do that there shouldn't be any problems.

I would assume there is some kind of weird interaction between CocoaPods, SourceKitten and xcodebuild. I am unsure where is the exact issue, maybe it's just a matter of updating version of Xcode version to 7.3 on machine that produces this callstack.

I would appreciate any help on this.

**Comment by orta** [comment]
@kzaher's point was correct, CocoaDocs was on Xcode 7.2 - I updated it today, and now the DocSets are up 👍
